language: ruby
rvm:
- 2.2.5
script:
- chmod +x ./scripts/deploy.sh
- gem install html-proofer
- bundle install
- bundle exec jekyll build
after_success:
- bash ./scripts/deploy.sh
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: qgIKBSSDFOYBuN1GgkAz3FU3jGUPZPpQS6lV9itkh+JjTY7KWyeBKFrbiPk6ovot9RRbpd23RMEyiuO2PAjFR8gwoPPuTXhNELyWh4tb6KhX9zyv5SrVmf+zb6TA2OTGSpxpvIBvPzRmnmkUOCd9C8j1K0eYDYwPOySb5ulhfaFI92jjiPk1YjjR37D75ydG14kbgjQVQQ4ZNw5jBCs53xe9MgG8KwEQ1tklJPC2x5+ZolnPH82s+WM3Q77oIaW4lH1xXn2KN8xTfJFgmNB0QZ50IWRlmN9f9z10bFglS+EdfLSMUSlm0cx/zdQc8DwNhfk04cZJlB8QLmd/IvyyjmgHfXaidgNorX+lQFvrUZlRlSXvgsgtmnSF3ONFxfhSKj6omHipd2amh5DcCSB+SUqWo/QZy/vuJfmHLwirbsNcMkfw6Tpzeu5zVCkvhM5LpxW6sdeUjTdrabt90l7H0Y9En9egFgWhKSvLTRstQ4/JbkEkYjGQIvtqEz/jPCvtjt9QFHZE11eh+hy1HhnxdUYp7B+eDxyjVUtBqMJMI6bUyTj0cUUmW+YE7HQcf/6STg0pHkVv1TRw4mSh8K8U6EHcoANcUqR9eSZ0uO4iMBI/J7rlMAp9Ikz07L7NxdpK4eNW02pRt/xKVmSKj7zGbeuFza9hUpOTEG3iWBSMhhk=
sudo: false
branches:
  only:
  - src
