language: ruby
rvm:
- 2.2.5

script:
- chmod +x ./scripts/deploy.sh
- gem install html-proofer
- bundle install
- bundle exec jekyll build
- bundle exec htmlproofer ./_site

after_success:
- '[ "${TRAVIS_BRANCH}" = "src" ] && ./scripts/deploy.sh || false'

notifications:
  irc: "irc.ozinger.org#hazealign"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
