language: ruby
rvm:
- 2.2.5

script:
- chmod +x ./scripts/deploy.sh
- gem install html-proofer
- bundle install
- bundle exec jekyll build

after_success:
- './scripts/deploy.sh'

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
