# Build settings
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from

# Site settings
title: "Haze Lee"
description: "책, 음악, 코딩, 피카츄와 함께하는 곳."
email: 'hazelee@re.aligni.st'
#blog logo
logo: "/assets/images/pikachu_logo.png"
# blog cover
cover: "/assets/images/background.jpg"

name: 'Haze Lee'
author: 'Haze Lee'
author_image: "/assets/images/author.jpg"

paginate: 5
exclude: [vendor]

url: "http://realignist.me" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@realignist'

#fill in disqus shortname to use disqus
disqus: realignist

timezone: Asia/Seoul
ampdir: amp

# social icons and sharing options
social:
  - icon: twitter
    url:  https://twitter.com/realignist
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: facebook
    url: http://fb.me/realignist
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon: github
    url:  https://github.com/hazealign
    desc: Fork me on github
    share_url:
    share_title:
    share_link:
